In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

AttributeError: partially initialized module 'pandas' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)

In [ ]:
df = pd.read_csv('datasets/Titanic-Dataset.csv')

In [ ]:
df.head(2)

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C

[2 rows x 12 columns]

In [ ]:
df['Sex'] = df['Sex'].map({'male':1,'female':0})

In [ ]:
df.head(2)

   PassengerId  Survived  Pclass  ...     Fare  Cabin  Embarked
0            1         0       3  ...   7.2500    NaN         S
1            2         1       1  ...  71.2833    C85         C

[2 rows x 12 columns]

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
X = df.drop(columns=['Cabin','Embarked','Survived','Name','Ticket','PassengerId'])
y=df['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
comparison_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(comparison_df.head(10))

     Actual  Predicted
709       1   0.052741
439       0   0.262634
840       0   0.161919
720       1   0.890875
39        1   0.670495
290       1   0.992209
300       1   0.632748
333       0   0.104295
208       1   0.700051
136       1   0.953298

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score,accuracy_score,precision_score,f1_score,recall_score
import numpy as np
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f"MAE: {mae}")
print(f"RMSE: {rmse}")
print(f"R2 Score: {r2}")

MAE: 0.28731873705976485
RMSE: 0.3681450393523375
R2 Score: 0.4411143627334001

In [ ]:
from sklearn.linear_model import Lasso
import seaborn as sns
alphas = [0.001,0.1,1,2,3,5,10,20,30,40,50,100]
mses=[]
# for a in alphas:
#     lasso_model = Lasso(alpha=a)
#     lasso_model.fit(X_train,y_train)
#     y_pred = lasso_model.predict(X_test)

#     mse = mean_squared_error(y_test,y_pred)
#     print(f"MSE for alpha = {a}: " ,mse)
#     mses.append(mse)
# sns.lineplot(x=alphas,y=mses,marker="o")

lasso_model = Lasso(alpha=0.001)
lasso_model.fit(X_train,y_train)
y_pred = lasso_model.predict(X_test)
r2=r2_score(y_test,y_pred)
print(r2*100)

44.068702506193524

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

y_pred= model.predict(X_test)

r2 = r2_score(y_test,y_pred)
r2

0.2167310167310167

In [ ]:
accuracyScore = accuracy_score(y_test, y_pred)
precisionScore = precision_score(y_test, y_pred)
recallScore = recall_score(y_test, y_pred)
f1Score = f1_score(y_test, y_pred)